export const fields = [
    {
        id: 'input_text',
        element: 'input',
        type: 'text',
        name: 'input_text',
        value: '',
        minLength: 4,
        className: 'form-control',
        placeholder: 'Name',
        required: true,
    },
    {
        id: 'input_email',
        element: 'input',
        type: 'email',
        name: 'input_email',
        value: '',
        minLength: 4,
        className: 'form-control',
        placeholder: 'Email',
        required: true,
    },
    {
        id: 'input_color',
        element: 'input',
        type: 'color',
        name: 'input_color',
        value: '',
        minLength: 4,
        className: 'form-control',
        placeholder: 'Color',
        required: true,
    },
];
