module.exports = ({ name, value, onChange }) => ([
    {
        title: 'Basic',
        fields: [
            [
                {
                    element: 'input',
                    type: 'text',
                    name: 'name',
                    className: 'form-control',
                    placeholder: 'Write unique field name',
                    required: true,
                    label: 'Input field name',
                    helpText: 'helpText',
                },
                {
                    element: 'input',
                    type: 'text',
                    name: 'className',
                    className: 'form-control',
                    label: 'Field class name',
                    helpText: 'helpText',
                },
                {
                    element: 'input',
                    type: 'number',
                    name: 'maxLength',
                    className: 'form-control',
                    label: 'Max length',
                    placeholder: 'Max length',
                },
            ],
            [
                {
                    element: 'input',
                    type: 'number',
                    name: 'minLength',
                    checked: false,
                    className: 'form-control',
                    label: 'Min length',
                    placeholder: 'Max length',
                },
                {
                    element: 'input',
                    type: 'text',
                    name: 'pattern',
                    className: 'form-control',
                    label: 'Pattern',
                    placeholder: 'Pattern',
                },
            ],
            [
                {
                    element: 'input',
                    type: 'text',
                    name: 'placeholder',
                    className: 'form-control',
                    label: 'Placeholder',
                    placeholder: 'Placeholder',
                },
                {
                    element: 'input',
                    type: 'checkbox',
                    name: 'readonly',
                    checked: false,
                    className: 'form-control',
                    label: 'Read only',
                },
                {
                    element: 'input',
                    type: 'checkbox',
                    name: 'required',
                    checked: true,
                    className: 'form-control',
                    label: 'Is input field required?',
                    helpText: 'helpText',
                },
            ],
        ],
    },
]);
